name: mass_pro
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# analyzer:
# strong-mode: true
# language:
# enableSuperMixins: true

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  intl: ^0.18.1
  flutter_styled_toast: ^2.1.3
  shared_preferences: ^2.0.15
  reflectable: ^4.0.0
  freezed_annotation: ^2.1.0
  rxdart: ^0.27.7
  dartx: ^1.1.0
  dartz: ^0.10.1
  dartlin: ^0.6.3
  get: ^4.6.5
  scrollable_positioned_list: ^0.3.5
  provider: ^6.0.5
#  flutter_riverpod: ^2.3.3
  flutter_riverpod: ^2.3.6
#  riverpod_annotation: ^2.0.3
  riverpod_annotation: ^2.1.1
  pointer_interceptor: ^0.9.3+2 # used in custom AlertDialog
  queue: ^3.1.0+1
  rounded_loading_button: ^2.1.0
  percent_indicator: ^4.2.3
  d2_remote:
    path: ./d2-remote

  # temp. Test dependencies
  # Replace later
  dio: ^4.0.4
  http_mock_adapter: ^0.3.2
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.1
  flutter_treeview: ^1.0.7+1
  table_calendar: ^3.0.9
#  sealed_annotations: ^1.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  built_value_generator: ^8.4.1
  #  sealed_generators: ^1.13.0
#  riverpod_generator: ^2.1.5
  riverpod_generator: ^2.2.4
#  riverpod_lint: ^1.1.7
  riverpod_lint: ^1.4.0
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/sample/dhis/
    - lib/main/l10n/locales_strings/
    - assets/images/
# analyzer:
#   strong-mode: true
#   language:
#     enableSuperMixins: true
