import 'package:d2_remote/core/mp/period/period_type.dart';
import 'package:d2_remote/modules/data/tracker/entities/enrollment.entity.dart';
import 'package:d2_remote/modules/metadata/program/entities/program.entity.dart';
import 'package:d2_remote/modules/metadata/program/entities/program_stage.entity.dart';

abstract class EnrollmentEventGeneratorRepository {
  Future<Enrollment> enrollment(String enrollmentUid);

  Future<List<ProgramStage>> enrollmentAutogeneratedEvents(
      String enrollmentUid, String programUid);

  Future<Program> enrollmentProgram(String programUid);

  Future<ProgramStage?> firstStagesInProgram(String programUid);

  Future<ProgramStage?> firstOpenAfterEnrollmentStage(String programUid);

  Future<bool> eventExistInEnrollment(String enrollmentUid, String stageUid);

  Future<String> eventUidInEnrollment(String enrollmentUid, String stageUid);

  Future<String> addEvent(String enrollmentUid, String programUid,
      String stageUid, String orgUnitUid, String activityUid);

  Future<DateTime> periodStartingDate(PeriodType periodType, DateTime date);

  Future<void> setEventDate(String eventUid, isScheduled, DateTime date);
}
