enum EventNonEditableReason {
  BLOCKED_BY_COMPLETION,
  EXPIRED,
  NO_DATA_WRITE_ACCESS,
  EVENT_DATE_IS_NOT_IN_ORGUNIT_RANGE,
  NO_CATEGORY_COMBO_ACCESS,
  ENROLLMENT_IS_NOT_OPEN,
  ORGUNIT_IS_NOT_IN_CAPTURE_SCOPE
}
